//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cls", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cls : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int iField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int i {
            get {
                return this.iField;
            }
            set {
                if ((this.iField.Equals(value) != true)) {
                    this.iField = value;
                    this.RaisePropertyChanged("i");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string s {
            get {
                return this.sField;
            }
            set {
                if ((object.ReferenceEquals(this.sField, value) != true)) {
                    this.sField = value;
                    this.RaisePropertyChanged("s");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SimpleServiceSoap")]
    public interface SimpleServiceSoap {
        
        // CODEGEN: Generating message contract since element name arr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EchoArr", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.EchoArrResponse EchoArr(ConsoleApplication1.ServiceReference1.EchoArrRequest request);
        
        // CODEGEN: Generating message contract since element name s from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EchoString", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.EchoStringResponse EchoString(ConsoleApplication1.ServiceReference1.EchoStringRequest request);
        
        // CODEGEN: Generating message contract since element name cls from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EchoComplex", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.EchoComplexResponse EchoComplex(ConsoleApplication1.ServiceReference1.EchoComplexRequest request);
        
        // CODEGEN: Generating message contract since element name cls from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EchoComplex1", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.EchoComplex1Response EchoComplex1(ConsoleApplication1.ServiceReference1.EchoComplex1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EchoArrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EchoArr", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference1.EchoArrRequestBody Body;
        
        public EchoArrRequest() {
        }
        
        public EchoArrRequest(ConsoleApplication1.ServiceReference1.EchoArrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EchoArrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.ServiceReference1.ArrayOfInt arr;
        
        public EchoArrRequestBody() {
        }
        
        public EchoArrRequestBody(ConsoleApplication1.ServiceReference1.ArrayOfInt arr) {
            this.arr = arr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EchoArrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EchoArrResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference1.EchoArrResponseBody Body;
        
        public EchoArrResponse() {
        }
        
        public EchoArrResponse(ConsoleApplication1.ServiceReference1.EchoArrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EchoArrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.ServiceReference1.ArrayOfInt EchoArrResult;
        
        public EchoArrResponseBody() {
        }
        
        public EchoArrResponseBody(ConsoleApplication1.ServiceReference1.ArrayOfInt EchoArrResult) {
            this.EchoArrResult = EchoArrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EchoStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EchoString", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference1.EchoStringRequestBody Body;
        
        public EchoStringRequest() {
        }
        
        public EchoStringRequest(ConsoleApplication1.ServiceReference1.EchoStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EchoStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        public EchoStringRequestBody() {
        }
        
        public EchoStringRequestBody(string s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EchoStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EchoStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference1.EchoStringResponseBody Body;
        
        public EchoStringResponse() {
        }
        
        public EchoStringResponse(ConsoleApplication1.ServiceReference1.EchoStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EchoStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EchoStringResult;
        
        public EchoStringResponseBody() {
        }
        
        public EchoStringResponseBody(string EchoStringResult) {
            this.EchoStringResult = EchoStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EchoComplexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EchoComplex", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference1.EchoComplexRequestBody Body;
        
        public EchoComplexRequest() {
        }
        
        public EchoComplexRequest(ConsoleApplication1.ServiceReference1.EchoComplexRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EchoComplexRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.ServiceReference1.Cls cls;
        
        public EchoComplexRequestBody() {
        }
        
        public EchoComplexRequestBody(ConsoleApplication1.ServiceReference1.Cls cls) {
            this.cls = cls;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EchoComplexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EchoComplexResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference1.EchoComplexResponseBody Body;
        
        public EchoComplexResponse() {
        }
        
        public EchoComplexResponse(ConsoleApplication1.ServiceReference1.EchoComplexResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EchoComplexResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.ServiceReference1.Cls EchoComplexResult;
        
        public EchoComplexResponseBody() {
        }
        
        public EchoComplexResponseBody(ConsoleApplication1.ServiceReference1.Cls EchoComplexResult) {
            this.EchoComplexResult = EchoComplexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EchoComplex1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EchoComplex1", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference1.EchoComplex1RequestBody Body;
        
        public EchoComplex1Request() {
        }
        
        public EchoComplex1Request(ConsoleApplication1.ServiceReference1.EchoComplex1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EchoComplex1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.ServiceReference1.Cls cls;
        
        public EchoComplex1RequestBody() {
        }
        
        public EchoComplex1RequestBody(ConsoleApplication1.ServiceReference1.Cls cls) {
            this.cls = cls;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EchoComplex1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EchoComplex1Response", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference1.EchoComplex1ResponseBody Body;
        
        public EchoComplex1Response() {
        }
        
        public EchoComplex1Response(ConsoleApplication1.ServiceReference1.EchoComplex1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EchoComplex1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.ServiceReference1.Cls EchoComplex1Result;
        
        public EchoComplex1ResponseBody() {
        }
        
        public EchoComplex1ResponseBody(ConsoleApplication1.ServiceReference1.Cls EchoComplex1Result) {
            this.EchoComplex1Result = EchoComplex1Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimpleServiceSoapChannel : ConsoleApplication1.ServiceReference1.SimpleServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleServiceSoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.SimpleServiceSoap>, ConsoleApplication1.ServiceReference1.SimpleServiceSoap {
        
        public SimpleServiceSoapClient() {
        }
        
        public SimpleServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.EchoArrResponse ConsoleApplication1.ServiceReference1.SimpleServiceSoap.EchoArr(ConsoleApplication1.ServiceReference1.EchoArrRequest request) {
            return base.Channel.EchoArr(request);
        }
        
        public ConsoleApplication1.ServiceReference1.ArrayOfInt EchoArr(ConsoleApplication1.ServiceReference1.ArrayOfInt arr) {
            ConsoleApplication1.ServiceReference1.EchoArrRequest inValue = new ConsoleApplication1.ServiceReference1.EchoArrRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.EchoArrRequestBody();
            inValue.Body.arr = arr;
            ConsoleApplication1.ServiceReference1.EchoArrResponse retVal = ((ConsoleApplication1.ServiceReference1.SimpleServiceSoap)(this)).EchoArr(inValue);
            return retVal.Body.EchoArrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.EchoStringResponse ConsoleApplication1.ServiceReference1.SimpleServiceSoap.EchoString(ConsoleApplication1.ServiceReference1.EchoStringRequest request) {
            return base.Channel.EchoString(request);
        }
        
        public string EchoString(string s) {
            ConsoleApplication1.ServiceReference1.EchoStringRequest inValue = new ConsoleApplication1.ServiceReference1.EchoStringRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.EchoStringRequestBody();
            inValue.Body.s = s;
            ConsoleApplication1.ServiceReference1.EchoStringResponse retVal = ((ConsoleApplication1.ServiceReference1.SimpleServiceSoap)(this)).EchoString(inValue);
            return retVal.Body.EchoStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.EchoComplexResponse ConsoleApplication1.ServiceReference1.SimpleServiceSoap.EchoComplex(ConsoleApplication1.ServiceReference1.EchoComplexRequest request) {
            return base.Channel.EchoComplex(request);
        }
        
        public ConsoleApplication1.ServiceReference1.Cls EchoComplex(ConsoleApplication1.ServiceReference1.Cls cls) {
            ConsoleApplication1.ServiceReference1.EchoComplexRequest inValue = new ConsoleApplication1.ServiceReference1.EchoComplexRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.EchoComplexRequestBody();
            inValue.Body.cls = cls;
            ConsoleApplication1.ServiceReference1.EchoComplexResponse retVal = ((ConsoleApplication1.ServiceReference1.SimpleServiceSoap)(this)).EchoComplex(inValue);
            return retVal.Body.EchoComplexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.EchoComplex1Response ConsoleApplication1.ServiceReference1.SimpleServiceSoap.EchoComplex1(ConsoleApplication1.ServiceReference1.EchoComplex1Request request) {
            return base.Channel.EchoComplex1(request);
        }
        
        public ConsoleApplication1.ServiceReference1.Cls EchoComplex1(ConsoleApplication1.ServiceReference1.Cls cls) {
            ConsoleApplication1.ServiceReference1.EchoComplex1Request inValue = new ConsoleApplication1.ServiceReference1.EchoComplex1Request();
            inValue.Body = new ConsoleApplication1.ServiceReference1.EchoComplex1RequestBody();
            inValue.Body.cls = cls;
            ConsoleApplication1.ServiceReference1.EchoComplex1Response retVal = ((ConsoleApplication1.ServiceReference1.SimpleServiceSoap)(this)).EchoComplex1(inValue);
            return retVal.Body.EchoComplex1Result;
        }
    }
}
